entryPoints:
  web:
    address: ":80"
#    http:
#      redirections:
#        entryPoint:
#          to: websecure
#          scheme: https
#          permanent: true
#  websecure:
#    address: ":443"
#    http:
#      tls:
#        certResolver: letsencrypt

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
  file:
    directory: conf.d


certificatesResolvers:
  letsencrypt:
    acme:
      email: "theo.julien.henry@gmail.com"
      storage: /etc/traefik/letsencrypt/acme.json
      dnsChallenge:
        provider: dynu

  #Always use this certificates resolver for testing to avoid rate limits
  letsencrypt-staging:
    acme:
      email: "theo.julien.henry@gmail.com"
      storage: /etc/traefik/letsencrypt/acme-staging.json  # Fichier séparé !
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: dynu