const NAVIGATE_PAGE = "NAVIGATE_PAGE";
const SERVER_NOTIFICATION = "SERVER_NOTIFICATION";
const SERVER_FORCE_DISCONNECT = "SERVER_FORCE_DISCONNECT";



export {
    NAVIGATE_PAGE,
    SERVER_NOTIFICATION, SERVER_FORCE_DISCONNECT
}