const NAVIGATE_PAGE = "NAVIGATE_PAGE";
const SERVER_NAVIGATE_PAGE = "SERVER_NAVIGATE_PAGE";
const SERVER_NOTIFICATION = "SERVER_NOTIFICATION";
const SERVER_ERROR = "SERVER_ERROR";
const SERVER_FORCE_DISCONNECT = "SERVER_FORCE_DISCONNECT";
const SET_USER_ID = "SET_USER_ID";



export {
    NAVIGATE_PAGE, SERVER_NAVIGATE_PAGE,
    SERVER_NOTIFICATION, SERVER_FORCE_DISCONNECT, SERVER_ERROR,
    SET_USER_ID
}