const TRANSIT_1 = "TRANSIT_1";
const TRANSIT_2 = "TRANSIT_2";
const TRANSIT_3 = "TRANSIT_3";
const TRANSIT_4 = "TRANSIT_4";
const SYSCON = "SYSCON";
const DATA_STORE = "DATA_STORE";
const PASSCODE_STORE = "PASSCODE_STORE";
const RESOURCE_STORE = "RESOURCE_STORE";
const WORD_SEARCH = "WORD_SEARCH";
const MAGIC_EYE = "MAGIC_EYE";
const PASSWORD_GUESS = "PASSWORD_GUESS";
const UNHACKABLE = "UNHACKABLE";
const MANUAL_1 = "MANUAL_1";
const MANUAL_2 = "MANUAL_2";
const MANUAL_3 = "MANUAL_3";


export {TRANSIT_1, TRANSIT_2, TRANSIT_3, TRANSIT_4, SYSCON, DATA_STORE,
    PASSCODE_STORE, RESOURCE_STORE, WORD_SEARCH, MAGIC_EYE, PASSWORD_GUESS,
    UNHACKABLE, MANUAL_1, MANUAL_2, MANUAL_3}