const REQUEST_SITE_FULL = "REQUEST_SITE_FULL";
const SERVER_SITE_FULL  = "SERVER_SITE_FULL";

const EDIT_SITE_DATA = "EDIT_SITE_DATA";
const SERVER_UPDATE_SITE_DATA = "SERVER_UPDATE_SITE_DATA";

const DRAG_DROP_START = "DRAG_START";
const DRAG_DROP_END = "DRAG_DROP_END";
const SERVER_ADD_NODE = "SERVER_ADD_NODE";

const MOVE_NODE = "MOVE_NODE";
const SERVER_MOVE_NODE = "SERVER_MOVE_NODE";

const ADD_CONNECTION = "ADD_CONNECTION";
const SERVER_ADD_CONNECTION = "SERVER_ADD_CONNECTION";

const DELETE_CONNECTIONS = "DELETE_CONNECTIONS";
const DELETE_NODE = "DELETE_NODE";
const SNAP = "SNAP";

const SELECT_NODE = "SELECT_NODE";

const EDIT_NETWORK_ID = "EDIT_NETWORK_ID";
const SERVER_UPDATE_NETWORK_ID = "SERVER_UPDATE_NETWORK_ID";
const EDIT_SERVICE_DATA = "EDIT_SERVICE_DATA";
const SERVER_UPDATE_SERVICE = "SERVER_UPDATE_SERVICE";

const SERVER_UPDATE_SITE_STATE = "SERVER_UPDATE_SITE_STATE";

const ADD_SERVICE = "ADD_SERVICE";
const SERVER_ADD_SERVICE = "SERVER_ADD_SERVICE";
const SELECT_SERVICE = "SELECT_SERVICE";
const REMOVE_SERVICE = "REMOVE_SERVICE";
const SERVER_NODE_UPDATED = "SERVER_NODE_UPDATED";
const SWAP_SERVICE_LAYER = "SWAP_SERVICE_LAYER";

export {
    REQUEST_SITE_FULL, SERVER_SITE_FULL,
    EDIT_SITE_DATA, SERVER_UPDATE_SITE_DATA,
    DRAG_DROP_START, DRAG_DROP_END, SERVER_ADD_NODE,
    MOVE_NODE, SERVER_MOVE_NODE,
    ADD_CONNECTION, SERVER_ADD_CONNECTION,
    DELETE_CONNECTIONS, DELETE_NODE, SNAP,
    SELECT_NODE,
    EDIT_SERVICE_DATA, SERVER_UPDATE_SERVICE, EDIT_NETWORK_ID, SERVER_UPDATE_NETWORK_ID,
    SERVER_UPDATE_SITE_STATE,
    ADD_SERVICE, SERVER_ADD_SERVICE, SELECT_SERVICE, REMOVE_SERVICE, SERVER_NODE_UPDATED, SWAP_SERVICE_LAYER
}