const SERVER_NOTIFICATION = "SERVER_NOTIFICATION";
const SERVER_FORCE_DISCONNECT = "SERVER_FORCE_DISCONNECT";

const REQUEST_SITE_FULL = "REQUEST_SITE_FULL";
const SERVER_SITE_FULL  = "SERVER_SITE_FULL";

const EDIT_SITE_DATA = "EDIT_SITE_DATA";
const SERVER_UPDATE_SITE_DATA = "SERVER_UPDATE_SITE_DATA";

const DRAG_DROP_START = "DRAG_START";
const DRAG_DROP_END = "DRAG_DROP_END";
const SERVER_ADD_NODE = "SERVER_ADD_NODE";

const MOVE_NODE = "MOVE_NODE";
const SERVER_MOVE_NODE = "SERVER_MOVE_NODE";

const ADD_CONNECTION = "ADD_CONNECTION";
const SERVER_ADD_CONNECTION = "SERVER_ADD_CONNECTION";

const DELETE_CONNECTIONS = "DELETE_CONNECTIONS";
const DELETE_NODE = "DELETE_NODE";
const SNAP = "SNAP";

const SELECT_NODE = "SELECT_NODE";

// const SERVER_DELETE_CONNECTIONS = "SERVER_DELETE_CONNECTIONS";
// const SERVER_DELETE_NODE = "SERVER_DELETE_NODE";

export {
    SERVER_NOTIFICATION, SERVER_FORCE_DISCONNECT,
    REQUEST_SITE_FULL, SERVER_SITE_FULL,
    EDIT_SITE_DATA, SERVER_UPDATE_SITE_DATA,
    DRAG_DROP_START, DRAG_DROP_END, SERVER_ADD_NODE,
    MOVE_NODE, SERVER_MOVE_NODE,
    ADD_CONNECTION, SERVER_ADD_CONNECTION,
    DELETE_CONNECTIONS, DELETE_NODE, SNAP,
    SELECT_NODE,
}