services:
  # config base on https://joeeey.com/blog/selfhosting-sso-with-traefik-keycloak-part-1/

  traefik:
    image: traefik:latest
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
#    environment:  For getting ssl certificat
#      NAMECHEAP_API_USER: '< username >'
#      NAMECHEAP_API_KEY: '< key >'
    volumes:
      - ./conf/traefik/traefik.yml:/traefik.yml
      - ./conf/traefik/conf.d:/conf.d
      - ./data/traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.route-reverseproxy.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.route-reverseproxy.service=api@internal"
    restart: unless-stopped

  keycloak:
    # internal: keycloak on port 8080
    image: quay.io/keycloak/keycloak:latest
    command: start
    environment:
      KC_HOSTNAME: 'auth.${DOMAIN}'
      KC_PROXY: 'edge'
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      KC_HTTP_ENABLED: true
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_STRICT: false
    volumes:
      - ./data/keycloak:/opt/keycloak/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.route-auth.rule=Host(`auth.${DOMAIN}`)"
      - "traefik.http.services.route-auth.loadbalancer.server.port=8080"
      # Redirect '/' to '/admin'
      - "traefik.http.middlewares.custom-redirect.redirectregex.regex=^https:\\/\\/([^\\/]+)\\/?$$"
      - "traefik.http.middlewares.custom-redirect.redirectregex.replacement=http://$$1/admin"
      - "traefik.http.routers.route-auth.middlewares=default@file,custom-redirect"
    restart: unless-stopped
    depends_on:
      - keycloak-db
      - traefik


# TODO mettre en place DB PostgreSQL for KeyCloak
# https://medium.com/@disa2aka/docker-deployments-for-keycloak-and-postgresql-e75707b155e5

  keycloak-db:
    container_name: keycloak-db
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  attack_vector_2-db:
    container_name: attack_vector_2-DB
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - TZ='Europe/Amsterdam'
    volumes:
      - mongo_data:/data/db
      - ./install/createUser.js:/docker-entrypoint-initdb.d/init.js:ro

volumes:
  postgres_data:
    driver: local
  mongo_data:
