import React from 'react'
import {TangleRoot} from "./tangle/TangleRoot";
import {PasswordRoot} from "./password/PasswordRoot";
import {WordSearchRoot} from "./wordsearch/WordSearchRoot";
import {NetwalkRoot} from "./netwalk/NetwalkRoot";
import {
    layerTypeFromIceId,
    NETWALK_ICE,
    PASSWORD_ICE,
    TANGLE_ICE,
    TAR_ICE,
    WORD_SEARCH_ICE,
    SWEEPER_ICE
} from "../../common/enums/LayerTypes";
import {TarRoot} from "./tar/TarRoot";
import {TopLevelError} from "../../common/component/TopLevelError";
import {SweeperRoot} from "./sweeper/SweeperRoot";

interface Props {
    iceId: string,
    nextUrl: string | null
}

export const SiteHackIce = (props: Props) => {

    const layerType = layerTypeFromIceId(props.iceId)

    switch (layerType) {
        case TANGLE_ICE: return <TangleRoot iceId={props.iceId} externalHack={false}/>
        case PASSWORD_ICE: return <PasswordRoot iceId={props.iceId} externalHack={false}/>
        case WORD_SEARCH_ICE: return <WordSearchRoot iceId={props.iceId} externalHack={false}/>
        case NETWALK_ICE: return <NetwalkRoot iceId={props.iceId} externalHack={false}/>
        case TAR_ICE: return <TarRoot iceId={props.iceId} externalHack={false}/>
        case SWEEPER_ICE: return <SweeperRoot iceId={props.iceId} externalHack={false} />
        default: return <TopLevelError error="Invalid connection"
                                       description={`(Unknown ice type: ${props.iceId} , maybe this QR/URL was generated by an different version of Attack Vector?)`}/>

    }
}
