entryPoints:
  web:
    address: ':80'
#    http:
#      redirections:
#        entryPoint:
#          to: websecure
#          scheme: https
#  websecure:
#    address: ':443'
#    http:
#      tls:
##        certresolver: lets-encrypt
#        domains:
#          - main: localhost
#            sans:
#              - '*.localhost'
#      middlewares:
#        - default@file

api:
  dashboard: true

# For retrieving certificate from your domain name registrar
# Exemple here are for namecheap domain name registrar

#certificatesResolvers:
#  lets-encrypt:
#    acme:
#      email: admin@example.com
#      storage: acme.json
#      dnsChallenge:
#        provider: namecheap

providers:
  docker:
    exposedByDefault: false
  file:
    directory: conf.d