server.port: 80

spring.servlet.multipart:
    file-size-threshold: 2KB
    max-file-size: 10MB
    max-request-size: 15MB

spring.data.mongodb.auto-index-creation: true

http-client.log-request: false

cors:
    allowedOrigins: "http://localhost,http://localhost:3000,https://av.eosfrontier.space,https://eosfrontier.space"
