const ENTER_SCAN = "ENTER_SCAN";
const SCAN_FOR_NAME =  "SCAN_FOR_NAME";
const RETRIEVE_USER_SCANS = "RETRIEVE_USER_SCANS";
const SERVER_RECEIVE_USER_SCANS = "SERVER_RECEIVE_USER_SCANS";

export { ENTER_SCAN, SCAN_FOR_NAME, RETRIEVE_USER_SCANS, SERVER_RECEIVE_USER_SCANS }