export const DELETE_SCAN = "DELETE_SCAN";
export const SCAN_FOR_NAME =  "SCAN_FOR_NAME";
export const RETRIEVE_USER_SCANS = "RETRIEVE_USER_SCANS";

export const SERVER_SITE_DISCOVERED = "SERVER_SITE_DISCOVERED";
