const ENTER_SCAN = "ENTER_SCAN";
const SERVER_SITE_DISCOVERED = "SERVER_SITE_DISCOVERED";
const SCAN_FOR_NAME =  "SCAN_FOR_NAME";
const RETRIEVE_USER_SCANS = "RETRIEVE_USER_SCANS";
const SERVER_RECEIVE_USER_SCANS = "SERVER_RECEIVE_USER_SCANS";


export { ENTER_SCAN, SERVER_SITE_DISCOVERED, SCAN_FOR_NAME, RETRIEVE_USER_SCANS, SERVER_RECEIVE_USER_SCANS }