const SCAN_NODE_INITIAL = "SCAN_NODE_INITIAL";
const SCAN_CONNECTIONS = "SCAN_CONNECTIONS";
const SCAN_NODE_DEEP = "SCAN_NODE_DEEP";

export {
    SCAN_NODE_INITIAL,
    SCAN_CONNECTIONS,
    SCAN_NODE_DEEP,
}
