const REQUEST_SCAN_FULL = "REQUEST_SCAN_FULL";
const SERVER_SCAN_FULL = "SERVER_SCAN_FULL";
const SERVER_PROBE_ACTION = "SERVER_PROBE_ACTION";

const PROBE_SCAN_NODE_INITIAL = "PROBE_SCAN_NODE_INITIAL";
const PROBE_SCAN_CONNECTIONS = "PROBE_SCAN_CONNECTIONS";
const PROBE_SCAN_NODE_DEEP = "PROBE_SCAN_NODE_DEEP";

export {
    REQUEST_SCAN_FULL,
    SERVER_SCAN_FULL,
    SERVER_PROBE_ACTION,
    PROBE_SCAN_NODE_INITIAL,
    PROBE_SCAN_CONNECTIONS,
    PROBE_SCAN_NODE_DEEP,
}