const REQUEST_SCAN_FULL = "REQUEST_SCAN_FULL";
const SERVER_SCAN_FULL = "SERVER_SCAN_FULL";
const SERVER_PROBE_LAUNCH = "SERVER_PROBE_LAUNCH";

const PROBE_SCAN_NODE = "PROBE_SCAN_NODE";
const SERVER_UPDATE_NODE_STATUS = "SERVER_UPDATE_NODE_STATUS";
const SERVER_DISCOVER_NODES = "SERVER_DISCOVER_NODES";
const AUTO_SCAN = "AUTO_SCAN";

export {
    REQUEST_SCAN_FULL,
    SERVER_SCAN_FULL,
    SERVER_PROBE_LAUNCH,
    PROBE_SCAN_NODE,
    SERVER_UPDATE_NODE_STATUS,
    SERVER_DISCOVER_NODES,
    AUTO_SCAN,
}