const REQUEST_SCAN_FULL = "REQUEST_SCAN_FULL";
const SERVER_SCAN_FULL = "SERVER_SCAN_FULL";
const SERVER_PROBE_LAUNCH = "SERVER_PROBE_LAUNCH";

const PROBE_SCAN_NODE = "PROBE_SCAN_NODE";
const SERVER_PROBE_SCAN_SUCCESS = "SERVER_PROBE_SCAN_SUCCESS";

export {
    REQUEST_SCAN_FULL,
    SERVER_SCAN_FULL,
    SERVER_PROBE_LAUNCH,
    PROBE_SCAN_NODE,
    SERVER_PROBE_SCAN_SUCCESS,
}