export const NAVIGATE_PAGE = "NAVIGATE_PAGE";
export const SERVER_NOTIFICATION = "SERVER_NOTIFICATION";
export const SERVER_ERROR = "SERVER_ERROR";
export const SERVER_DISCONNECT = "SERVER_DISCONNECT";
export const SERVER_FORCE_DISCONNECT = "SERVER_FORCE_DISCONNECT";
export const SET_USER_ID = "SET_USER_ID";
export const SERVER_TIME_SYNC = "SERVER_TIME_SYNC";
