export const HACKER_RUN_ACTIVITY_SCANNING = "SCANNING";
export const HACKER_RUN_ACTIVITY_STARTING = "STARTING";
export const HACKER_RUN_ACTIVITY_AT_NODE = "AT_NODE";
export const HACKER_RUN_ACTIVITY_MOVING = "MOVING";