const UNDISCOVERED = "UNDISCOVERED";
const DISCOVERED = "DISCOVERED";
const TYPE = "TYPE";
const LAYERS_NO_CONNECTIONS = "LAYERS_NO_CONNECTIONS";
const CONNECTIONS = "CONNECTIONS";
const LAYERS = "LAYERS";
const FREE = "FREE";
const PROTECTED = "PROTECTED";
const HACKED = "HACKED";


export {
    UNDISCOVERED,
    DISCOVERED,
    TYPE,
    LAYERS_NO_CONNECTIONS,
    CONNECTIONS,
    LAYERS,
    FREE,
    PROTECTED,
    HACKED,
}