const UNDISCOVERED = "UNDISCOVERED";
const DISCOVERED = "DISCOVERED";
const TYPE = "TYPE";
const SERVICES_NO_CONNECTIONS = "SERVICES_NO_CONNECTIONS";
const CONNECTIONS = "CONNECTIONS";
const SERVICES = "SERVICES";
const FREE = "FREE";
const PROTECTED = "PROTECTED";
const HACKED = "HACKED";


export {
    UNDISCOVERED,
    DISCOVERED,
    TYPE,
    SERVICES_NO_CONNECTIONS,
    CONNECTIONS,
    SERVICES,
    FREE,
    PROTECTED,
    HACKED,
}