const TERMINAL_KEY_PRESS = "TERMINAL_KEY_PRESS";
const TERMINAL_SUBMIT = "TERMINAL_SUBMIT";
const TERMINAL_TICK = "TERMINAL_TICK";
const TERMINAL_RECEIVE = "TERMINAL_RECEIVE";
const SERVER_TERMINAL_RECEIVE = "SERVER_TERMINAL_RECEIVE";

export { TERMINAL_KEY_PRESS, TERMINAL_SUBMIT, TERMINAL_TICK, TERMINAL_RECEIVE, SERVER_TERMINAL_RECEIVE};