const TERMINAL_KEY_PRESS = "TERMINAL_KEY_PRESS";
const TERMINAL_SUBMIT = "TERMINAL_SUBMIT";
const TERMINAL_TICK = "TERMINAL_TICK";
const TERMINAL_RECEIVE = "TERMINAL_RECEIVE";
const SERVER_TERMINAL_RECEIVE = "SERVER_TERMINAL_RECEIVE";
const TERMINAL_CLEAR = "TERMINAL_CLEAR";

const TERMINAL_LOCK = "TERMINAL_LOCK";
const TERMINAL_UNLOCK = "TERMINAL_UNLOCK";

const SERVER_USER_DC = "SERVER_USER_DC";

export {
    TERMINAL_KEY_PRESS, TERMINAL_SUBMIT, TERMINAL_TICK, TERMINAL_RECEIVE, TERMINAL_CLEAR,
    SERVER_USER_DC,
    SERVER_TERMINAL_RECEIVE,
    TERMINAL_LOCK, TERMINAL_UNLOCK };