name: Build and Deploy to ECR
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Build-backend-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: cd backend directory
        run: cd backend

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: check results
        run: ls -R target
