name: Build & release jar file when v* tag is pushed

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        working-directory: ./backend
        run: mvn --batch-mode --update-snapshots package

      - name: View build results
        working-directory: ./backend
        run: ls -als target/

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name.startsWith('v') && github.ref_name[1:] || github.ref_name }}
          files: backend/target/app.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
